# Site settings
author: Anna Bergland
title: Full Throttle 
header-img: img/home-bg.png
email: berglandhanna@gmail.com
copyright_name: Anna Bergland
description: > # this means to ignore newlines until "baseurl:"
  A Journey Through Tibet to Everest
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HannaStrezh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
